apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: acs-helloworld-{{.Release.Name}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: acs-helloworld-{{.Release.Name}}
    spec:
      containers:
      - name: acs-helloworld-{{.Release.Name}}
        image: {{ .Values.image }}
        ports:
        - containerPort: 80
        env:
        - name: TITLE
          value: {{ .Values.title }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
spec:
  type: {{ .Values.serviceType }}
  ports:
  - port: 80
  selector:
    app: acs-helloworld-{{.Release.Name}}