apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: azure-rediscache-{{.Release.Name}}
  namespace: default
spec:
  clusterServiceClassExternalName: azure-rediscache
  clusterServicePlanExternalName: basic
  parameters:
    location: eastus
    resourceGroup: azure-rediscache-{{.Release.Name}}
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: azure-rediscache-binding-{{.Release.Name}}
  namespace: default
spec:
  instanceRef:
    name: azure-rediscache-{{.Release.Name}}
  secretName: azure-rediscache-secret-{{.Release.Name}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-front-{{.Release.Name}}
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: vote-front-{{.Release.Name}}
    spec:
      containers:
      - name: azure-vote-front
        image: neilpeterson/azure-vote-front:v3
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: REDIS
          valueFrom:
            secretKeyRef:
              key: host
              name: azure-rediscache-secret-{{.Release.Name}}
        - name: REDIS_PWD
          valueFrom:
            secretKeyRef:
              key: password
              name: azure-rediscache-secret-{{.Release.Name}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceNameFront }}
  labels:
    name: {{ .Values.serviceNameFront }}
spec:
  type: {{ .Values.serviceType }}
  ports:
  - port: 80
  selector:
    app: vote-front-{{.Release.Name}}